#!/bin/bash
/usr/bin/env bash
# 07-certbot-ssl.sh - Let's Encrypt SSL certificate module
# Installs certbot, requests certificate and configures Apache/Nginxset -euo pipefail
MODULE_NAME="Let's Encrypt SSL Certificate"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALLER_ROOT="$(dirname "$SCRIPT_DIR")"
# Source utilitiessource "${INSTALLER_ROOT}/utils/colors.sh"source "${INSTALLER_ROOT}/utils/logger.sh"source "${INSTALLER_ROOT}/utils/validate.sh"source "${INSTALLER_ROOT}/utils/menu.sh"
# Load configuration
if [[ -f "${INSTALLER_ROOT}/.env" ]]; then  set -a  source "${INSTALLER_ROOT}/.env"  set +a
fi
# Module startlog_module_start "$MODULE_NAME"
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Pre-check DNS and ports
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#precheck_ssl_prereqs() {  local domain="$1"    log_info "Pre-verifica prerequisiti SSL..."    
# DNS check  
echo -n "  - DNS $domain: "  if host "$domain" >/dev/null 2>&1; then    local resolved_ip    resolved_ip=$(host "$domain" | grep 'has address' | awk '{print $NF}' | head -1)    
echo "OK (risolve a $resolved_ip)"  else    log_warning "Risoluzione DNS fallita per $domain"    return 1  fi    
# Port 80 check  
echo -n "  - Porta 80: "  if ss -tulpn | grep -q ':80 '; then    
echo "OK (in ascolto)"  else    log_warning "Nessun processo in ascolto sulla porta 80"    return 1  fi    
# Port 443 check  
echo -n "  - Porta 443: "  if ss -tulpn | grep -q ':443 '; then    
echo "OK (in ascolto)"  else    log_warning "Nessun processo in ascolto sulla porta 443"  fi
echo ""  return 0}
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Install certbot
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#install_certbot() {  local webserver="${1:-apache}"    log_info "Installazione Certbot..."    
# Base certbot  if ! log_command "apt-get install -y certbot"; then    log_error "Failed to install certbot"    return 1  fi    
# Webserver plugin  case "$webserver" in    apache)      log_info "Installazione plugin Apache..."      if ! log_command "apt-get install -y python3-certbot-apache"; then        log_error "Failed to install certbot Apache plugin"        return 1      fi      ;;    nginx)      log_info "Installazione plugin Nginx..."      if ! log_command "apt-get install -y python3-certbot-nginx"; then        log_error "Failed to install certbot Nginx plugin"        return 1      fi      ;;    standalone)      log_info "Modalit├á standalone selezionata (nessun plugin webserver)"      ;;    *)      log_error "Webserver non vali
do: $webserver"      return 1      ;;  esac    log_success "Certbot installato con successo"}
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Configure certbot CLI
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#configure_certbot_cli() {  local email="$1"    log_info "Configurazione certbot CLI..."    mkdir -p /etc/letsencrypt  local cli_ini="/etc/letsencrypt/cli.ini"    cat > "$cli_ini" <<EOF
# Certbot CLI configurationemail = $emailagree-tos = truenon-interactive = truequiet = trueEOF    log_success "Certbot CLI configurato: $cli_ini"}
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Request certificate
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#request_certificate() {  local webserver="$1"  local domain="$2"    log_info "Richiesta certificato Let's Encrypt per $domain..."    
# Pre-check  if ! precheck_ssl_prereqs "$domain"; then    log_error "Pre-check fallito. Verificare DNS e porte prima di procedere."    return 1  fi    
# Request certificate  if ! certbot certonly --"$webserver" -d "$domain"; then    log_error "Richiesta certificato fallita"    return 1  fi    log_success "Certificato ottenuto per $domain"}
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Configure Apache with Let's Encrypt
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#configure_apache_ssl() {  local domain="$1"  local redirect_to_site="${2:-true}"  local default_site="${3:-monitoring}"  local apache_conf="/etc/apache2/sites-available/checkmk.conf"    log_info "Configurazione Apache con certificato Let's Encrypt..."    
# Backup existing config  if [[ -f "$apache_conf" ]]; then    local backup    backup="${apache_conf}.backup-$(date +%Y%m%d-%H%M%S)"    cp "$apache_conf" "$backup"    log_debug "Backup creato: $backup"  fi    if [[ "$redirect_to_site" == "true" ]]; then    
# Config with redirect to site    cat > "$apache_conf" <<EOF<VirtualHost *:80>    ServerName $domain    
# Redirect HTTP to HTTPS    RewriteEngine On    RewriteCond %{HTTPS} off    RewriteRule ^(.*)$ https://%{HTTP_HOST}\$1 [
R=301,L]</VirtualHost><VirtualHost *:443>    ServerName $domain    
# SSL Configuration (Let's Encrypt)    SSLEngine on    SSLCertificateFile /etc/letsencrypt/live/$domain/fullchain.pem    SSLCertificateKeyFile /etc/letsencrypt/live/$domain/privkey.pem    
# Redirect root to CheckMK site    RewriteEngine On    RewriteRule ^/?$ /$default_site/ [
R=301,L]    
# Proxy to CheckMK site    ProxyPreserveHost On    ProxyPass /$default_site/ http://127.0.0.1:5000/$default_site/    ProxyPassReverse /$default_site/ http://127.0.0.1:5000/$default_site/    
# WebSocket support    RewriteCond %{HTTP:Upgrade} websocket [NC]    RewriteCond %{HTTP:Connection} upgrade [NC]    RewriteRule ^/$default_site/(.*) "ws://127.0.0.1:5000/$default_site/\$1" [P,L]    
# Security headers    Header always set Strict-Transport-Security "max-age=31536000"    Header always set X-Frame-Options "SAMEORIGIN"    Header always set X-Content-Type-Options "nosniff"</VirtualHost>EOF  else    
# Config without redirect (proxy root)    cat > "$apache_conf" <<EOF<VirtualHost *:80>    ServerName $domain    
# Redirect HTTP to HTTPS    RewriteEngine On    RewriteCond %{HTTPS} off    RewriteRule ^(.*)$ https://%{HTTP_HOST}\$1 [
R=301,L]</VirtualHost><VirtualHost *:443>    ServerName $domain    
# SSL Configuration (Let's Encrypt)    SSLEngine on    SSLCertificateFile /etc/letsencrypt/live/$domain/fullchain.pem    SSLCertificateKeyFile /etc/letsencrypt/live/$domain/privkey.pem    
# Proxy to CheckMK    ProxyPreserveHost On    ProxyPass / http://127.0.0.1:5000/    ProxyPassReverse / http://127.0.0.1:5000/    
# WebSocket support    RewriteEngine On    RewriteCond %{HTTP:Upgrade} websocket [NC]    RewriteCond %{HTTP:Connection} upgrade [NC]    RewriteRule ^/?(.*) "ws://127.0.0.1:5000/\$1" [P,L]    
# Security headers    Header always set Strict-Transport-Security "max-age=31536000"    Header always set X-Frame-Options "SAMEORIGIN"    Header always set X-Content-Type-Options "nosniff"</VirtualHost>EOF  fi    
# Enable site and disable default  log_command "a2ensite checkmk.conf" || true  log_command "a2dissite 000-default.conf" || true    
# Test and reload  if ! apache2ctl configtest; then    log_error "Configurazione Apache non valida"    return 1  fi    log_command "systemctl restart apache2"    log_success "Apache configurato con certificato Let's Encrypt per $domain"}
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Configure Nginx with Let's Encrypt
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#configure_nginx_ssl() {  local domain="$1"  local redirect_to_site="${2:-true}"  local default_site="${3:-monitoring}"  local nginx_conf="/etc/nginx/sites-available/checkmk.conf"    log_info "Configurazione Nginx con certificato Let's Encrypt..."    mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled    if [[ "$redirect_to_site" == "true" ]]; then    cat > "$nginx_conf" <<EOFserver {    listen 80;    server_name $domain;    return 301 https://\$host\$request_uri;}server {    listen 443 ssl;    server_name $domain;    ssl_certificate     /etc/letsencrypt/live/$domain/fullchain.pem;    ssl_certificate_key /etc/letsencrypt/live/$domain/privkey.pem;    
# Redirect root to site    location = / {        return 301 /$default_site/;    }    
# Proxy site path    location /$default_site/ {        proxy_set_header Host \$host;        proxy_set_header X-Real-IP \$remote_addr;        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;        proxy_set_header X-Forwarded-Proto \$scheme;        proxy_http_version 1.1;        proxy_set_header Upgrade \$http_upgrade;        proxy_set_header Connection "upgrade";        proxy_pass http://127.0.0.1:5000/$default_site/;    }}EOF  else    cat > "$nginx_conf" <<EOFserver {    listen 80;    server_name $domain;    return 301 https://\$host\$request_uri;}server {    listen 443 ssl;    server_name $domain;    ssl_certificate     /etc/letsencrypt/live/$domain/fullchain.pem;    ssl_certificate_key /etc/letsencrypt/live/$domain/privkey.pem;    location / {        proxy_set_header Host \$host;        proxy_set_header X-Real-IP \$remote_addr;        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;        proxy_set_header X-Forwarded-Proto \$scheme;        proxy_http_version 1.1;        proxy_set_header Upgrade \$http_upgrade;        proxy_set_header Connection "upgrade";        proxy_pass http://127.0.0.1:5000/;    }}EOF  fi    ln -sf "$nginx_conf" "/etc/nginx/sites-enabled/checkmk.conf"    if ! nginx -t; then    log_error "Configurazione Nginx non valida"    return 1  fi    log_command "systemctl reload nginx"    log_success "Nginx configurato con certificato Let's Encrypt per $domain"}
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Main execution
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#main() {  local webserver="${LETSENCRYPT_WEBSERVER:-apache}"  local email="${LETSENCRYPT_EMAIL:-}"  local domain="${LETSENCRYPT_DOMAIN:-}"  local redirect_to_site="${LETSENCRYPT_REDIRECT_TO_SITE:-true}"  local default_site="${CHECKMK_SITE_NAME:-monitoring}"    
# Validate required variables  if [[ -z "$email" ]]; then    log_error "LETSENCRYPT_EMAIL not set in .env"    exit 1  fi    if [[ -z "$domain" ]]; then    log_error "LETSENCRYPT_DOMAIN not set in .env"    exit 1  fi    
# Install certbot  install_certbot "$webserver"    
# Configure CLI  configure_certbot_cli "$email"    
# Request certificate  request_certificate "$webserver" "$domain"    
# Configure webserver  case "$webserver" in    apache)      configure_apache_ssl "$domain" "$redirect_to_site" "$default_site"      ;;    nginx)      configure_nginx_ssl "$domain" "$redirect_to_site" "$default_site"      ;;    standalone)      log_warning "Webserver standalone: configurazione manuale necessaria"      ;;  esac    log_module_complete "$MODULE_NAME"}
# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then  main "$@"fi
