#!/usr/bin/env python3
"""
create_rules_clients.py - Crea rules.mk con regole standard per folder CheckMK

Applica le 3 regole standard alla folder indicata:
  1. passive_checks_enabled = 0  (disabilita passive checks)
  2. host_check_commands → check_windows_alive -H $HOSTADDRESS$  (ARP via nmap)
  3. ignored_services ['PING']  (rimuove servizio PING dall'inventario)

Usage (come root):
  python3 create_rules_clients.py --folder clients
  python3 create_rules_clients.py --folder clients --dry-run

Version: 1.0.0
"""

import argparse
import os
import sys
import uuid

VERSION = "1.0.0"

WATO_BASE = "/omd/sites/monitoring/etc/check_mk/conf.d/wato"
OMD_USER  = "monitoring"


def build_rules_mk() -> str:
    return f"""# Written by Checkmk store
# Generated by create_rules_clients.py v{VERSION}


extra_service_conf.setdefault('passive_checks_enabled', [])

extra_service_conf['passive_checks_enabled'] = [
{{'id': '{uuid.uuid4()}', 'value': '0', 'condition': {{'host_folder': '/%s/' % FOLDER_PATH}}, 'options': {{'disabled': False}}}},
] + extra_service_conf['passive_checks_enabled']



globals().setdefault('host_check_commands', [])

host_check_commands = [
{{'id': '{uuid.uuid4()}', 'value': ('custom', 'check_windows_alive -H $HOSTADDRESS$'), 'condition': {{'host_folder': '/%s/' % FOLDER_PATH}}, 'options': {{'description': 'Windows workstations ARP check via nmap (bypassa Windows Firewall)', 'disabled': False}}}},
] + host_check_commands


globals().setdefault('ignored_services', [])

ignored_services = [
{{'id': '{uuid.uuid4()}', 'value': ['PING'], 'condition': {{'host_folder': '/%s/' % FOLDER_PATH}}, 'options': {{'description': 'Rimuovi servizio PING dai workstation Windows (host check gia via ARP)', 'disabled': False}}}},
] + ignored_services
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=f"Crea rules.mk per folder WATO v{VERSION}")
    parser.add_argument("--folder", required=True, help="Nome folder WATO (es: clients)")
    parser.add_argument("--dry-run", action="store_true", help="Mostra contenuto senza scrivere")
    args = parser.parse_args()

    print(f"create_rules_clients.py v{VERSION}")

    folder_path = os.path.join(WATO_BASE, args.folder)
    rules_path  = os.path.join(folder_path, "rules.mk")

    if not os.path.isdir(folder_path):
        print(f"ERRORE: Folder non trovata: {folder_path}")
        return 1

    content = build_rules_mk()

    if args.dry_run:
        print(f"\n[DRY RUN] Scriverebbe: {rules_path}")
        print("--- Contenuto ---")
        print(content)
        return 0

    if os.path.exists(rules_path):
        print(f"ATTENZIONE: {rules_path} esiste già, sovrascrittura.")

    with open(rules_path, "w") as f:
        f.write(content)

    try:
        import pwd
        pw = pwd.getpwnam(OMD_USER)
        os.chown(rules_path, pw.pw_uid, pw.pw_gid)
        print(f"Permessi: chown {OMD_USER} {rules_path}")
    except Exception as e:
        print(f"Permessi: skip ({e})")

    print(f"OK: {rules_path} scritto")
    print("Ora esegui: su - monitoring -c 'cmk -O'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
