#!/usr/bin/env bash
set -euo pipefail

# checkmk-tuning-interactive.sh
# Tuning interattivo (semplice) per Checkmk RAW / OMD (Nagios core).
# Output semplice (ASCII-only), senza banner/colori.

SITE="${SITE:-monitoring}"
SITEPATH="/opt/omd/sites/$SITE"
NAGIOS_CFG="$SITEPATH/etc/nagios/nagios.d/tuning.cfg"
GLOBAL_MK="$SITEPATH/etc/check_mk/conf.d/wato/global.mk"
BACKUP_DIR="/root/checkmk_tuning_backup_$(date +%Y%m%d_%H%M%S)"

die() { echo "[ERR] $*" >&2; exit 1; }
log() { echo "[INFO] $*"; }
warn() { echo "[WARN] $*"; }

require_root() {
	[[ ${EUID:-$(id -u)} -eq 0 ]] || die "eseguire come root (sudo)"
}

need_cmd() {
	command -v "$1" >/dev/null 2>&1 || die "comando mancante: $1"
}

read_cfg_value() {
	local key="$1" file="$2" v
	v="$(grep -E "^${key}=" "$file" 2>/dev/null | head -n1 | cut -d= -f2- | xargs || true)"
	if [[ -z "$v" ]]; then
		echo "(non impostato)"
	else
		echo "$v"
	fi
}

ensure_global_mk_line() {
	local line="$1"
	mkdir -p "$(dirname "$GLOBAL_MK")"
	touch "$GLOBAL_MK"
	grep -Fqx "$line" "$GLOBAL_MK" 2>/dev/null || echo "$line" >> "$GLOBAL_MK"
}

main() {
	require_root
	need_cmd omd

	[[ -d "$SITEPATH" ]] || die "sito non trovato: $SITE ($SITEPATH)"

	mkdir -p "$BACKUP_DIR"
	[[ -f "$NAGIOS_CFG" ]] && cp -a "$NAGIOS_CFG" "$BACKUP_DIR/" || true
	[[ -f "$GLOBAL_MK" ]] && cp -a "$GLOBAL_MK" "$BACKUP_DIR/" || true

	echo "Checkmk tuning (interactive)"
	echo "Sito:   $SITE"
	echo "Backup: $BACKUP_DIR"
	echo

	current_conc="$(read_cfg_value max_concurrent_checks "$NAGIOS_CFG")"
	current_serv_tmout="$(read_cfg_value service_check_timeout "$NAGIOS_CFG")"
	current_host_tmout="$(read_cfg_value host_check_timeout "$NAGIOS_CFG")"
	current_sleep="$(read_cfg_value sleep_time "$NAGIOS_CFG")"
	current_delay="$(read_cfg_value service_inter_check_delay_method "$NAGIOS_CFG")"

	echo "Impostazioni attuali ($NAGIOS_CFG):"
	echo "  max_concurrent_checks            = $current_conc"
	echo "  service_check_timeout            = $current_serv_tmout"
	echo "  host_check_timeout               = $current_host_tmout"
	echo "  sleep_time                       = $current_sleep"
	echo "  service_inter_check_delay_method = $current_delay"
	echo

	echo "Inserisci i nuovi valori (invio = default suggerito)"
	read -r -p "max_concurrent_checks [30]: " new_conc
	read -r -p "service_check_timeout (sec) [60]: " new_serv_tmout
	read -r -p "host_check_timeout (sec) [60]: " new_host_tmout
	read -r -p "sleep_time (sec) [0.25]: " new_sleep
	read -r -p "inter_check_delay_method (n/s/d) [s]: " new_delay

	new_conc="${new_conc:-30}"
	new_serv_tmout="${new_serv_tmout:-60}"
	new_host_tmout="${new_host_tmout:-60}"
	new_sleep="${new_sleep:-0.25}"
	new_delay="${new_delay:-s}"

	echo
	echo "Riepilogo nuovi valori:"
	echo "  max_concurrent_checks            = $new_conc"
	echo "  service_check_timeout            = $new_serv_tmout"
	echo "  host_check_timeout               = $new_host_tmout"
	echo "  sleep_time                       = $new_sleep"
	echo "  service_inter_check_delay_method = $new_delay"
	echo
	read -r -p "Applicare queste modifiche? [y/N]: " confirm
	confirm="${confirm:-N}"
	[[ "$confirm" =~ ^[Yy]$ ]] || { log "Annullato"; exit 0; }

	mkdir -p "$(dirname "$NAGIOS_CFG")"
	cat > "$NAGIOS_CFG" <<EOF
# Generated by checkmk-tuning-interactive.sh on $(date +%F_%T)
max_concurrent_checks=$new_conc
service_check_timeout=$new_serv_tmout
host_check_timeout=$new_host_tmout
sleep_time=$new_sleep
service_inter_check_delay_method=$new_delay
EOF

	ensure_global_mk_line "service_check_timeout = $new_serv_tmout"
	ensure_global_mk_line "use_cache_for_checking = True"

	log "Riavvio sito: $SITE"
	omd restart "$SITE"

	nagios_log="$SITEPATH/var/nagios/nagios.log"
	echo
	if [[ -f "$nagios_log" ]]; then
		echo "Ultime righe log Nagios ($nagios_log):"
		tail -n 10 "$nagios_log" || true
	else
		warn "Log Nagios non trovato: $nagios_log"
	fi

	echo
	log "Completato. Backup: $BACKUP_DIR"
}

main "$@"
