Inserisci uno o piÔö£├óÔö¼Ôòú host separati da spazi:marziodemo proxmox01 rocky01Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Ultima versione trovata: - DEB: https://monitoring.nethlab.it/monitoring/check_mk/agents/check-mk-agent_2.4.0p12-1_all.deb - RPM: https://monitoring.nethlab.it/monitoring/check_mk/agents/check-mk-agent-2.4.0p12-1.noarch.rpm============================Ôö£├│Ôö╝┬ÑÔö¼├¡Ôö£┬╗Ôö¼┬®Ôö¼├à  Installo + configuro marziodemo============================Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Host RHEL/CentOS/Rocky rilevato, installo RPM...Verifying...                          
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Preparing...                          
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Updating / installing...   1:check-mk-agent-2.4.0p12-1       
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Disabilito TLS e socket systemd standard...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Creo unit systemd per agent plain...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Ricarico systemd...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Abilito e avvio il nuovo socket...Ôö£├│Ôö╝├┤├ö├ç┬¬ Plain agent attivo. Test locale:<<<check_mk>>>Version: 2.4.0p12Hostname: marziodemoAgentOS: linuxUptime: 12345============================Ôö£├│Ôö╝┬ÑÔö¼├¡Ôö£┬╗Ôö¼┬®Ôö¼├à  Installo + configuro proxmox01============================Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Host Debian/Ubuntu rilevato, installo DEB...Selecting previously unselected package check-mk-agent.(Reading database ... 123456 files and directories currently installed.)Preparing to unpack .../check-mk-agent_2.4.0p12-1_all.deb ...Unpacking check-mk-agent (2.4.0p12-1) ...Setting up check-mk-agent (2.4.0p12-1) ...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Disabilito TLS e socket systemd standard...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Creo unit systemd per agent plain...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Ricarico systemd...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Abilito e avvio il nuovo socket...Ôö£├│Ôö╝├┤├ö├ç┬¬ Plain agent attivo. Test locale:<<<check_mk>>>Version: 2.4.0p12Hostname: proxmox01AgentOS: linuxUptime: 6789============================Ôö£├│Ôö╝┬ÑÔö¼├¡Ôö£┬╗Ôö¼┬®Ôö¼├à  Installo + configuro rocky01============================Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Host RHEL/CentOS/Rocky rilevato, installo RPM...Verifying...                          
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Preparing...                          
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Updating / installing...   1:check-mk-agent-2.4.0p12-1       
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Disabilito TLS e socket systemd standard...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Creo unit systemd per agent plain...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Ricarico systemd...Ôö£ÔûæÔö╝┬®├ö├ç├┐├ö├çÔûæ Abilito e avvio il nuovo socket...Ôö£├│Ôö╝├┤├ö├ç┬¬ Plain agent attivo. Test locale:<<<check_mk>>>Version: 2.4.0p12Hostname: rocky01AgentOS: linuxUptime: 4321
