Inserisci uno o pi├â┬╣ host separati da spazi:marziodemo proxmox01 rocky01├░┼©ÔÇÿÔÇ░ Ultima versione trovata: - DEB: https://monitoring.nethlab.it/monitoring/check_mk/agents/check-mk-agent_2.4.0p12-1_all.deb - RPM: https://monitoring.nethlab.it/monitoring/check_mk/agents/check-mk-agent-2.4.0p12-1.noarch.rpm============================├ó┼¥┬í├»┬©┬Å  Installo + configuro marziodemo============================├░┼©ÔÇÿÔÇ░ Host RHEL/CentOS/Rocky rilevato, installo RPM...Verifying...                          
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Preparing...                          
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Updating / installing...   1:check-mk-agent-2.4.0p12-1       
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]├░┼©ÔÇÿÔÇ░ Disabilito TLS e socket systemd standard...├░┼©ÔÇÿÔÇ░ Creo unit systemd per agent plain...├░┼©ÔÇÿÔÇ░ Ricarico systemd...├░┼©ÔÇÿÔÇ░ Abilito e avvio il nuovo socket...├ó┼ôÔÇª Plain agent attivo. Test locale:<<<check_mk>>>Version: 2.4.0p12Hostname: marziodemoAgentOS: linuxUptime: 12345============================├ó┼¥┬í├»┬©┬Å  Installo + configuro proxmox01============================├░┼©ÔÇÿÔÇ░ Host Debian/Ubuntu rilevato, installo DEB...Selecting previously unselected package check-mk-agent.(Reading database ... 123456 files and directories currently installed.)Preparing to unpack .../check-mk-agent_2.4.0p12-1_all.deb ...Unpacking check-mk-agent (2.4.0p12-1) ...Setting up check-mk-agent (2.4.0p12-1) ...├░┼©ÔÇÿÔÇ░ Disabilito TLS e socket systemd standard...├░┼©ÔÇÿÔÇ░ Creo unit systemd per agent plain...├░┼©ÔÇÿÔÇ░ Ricarico systemd...├░┼©ÔÇÿÔÇ░ Abilito e avvio il nuovo socket...├ó┼ôÔÇª Plain agent attivo. Test locale:<<<check_mk>>>Version: 2.4.0p12Hostname: proxmox01AgentOS: linuxUptime: 6789============================├ó┼¥┬í├»┬©┬Å  Installo + configuro rocky01============================├░┼©ÔÇÿÔÇ░ Host RHEL/CentOS/Rocky rilevato, installo RPM...Verifying...                          
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Preparing...                          
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]Updating / installing...   1:check-mk-agent-2.4.0p12-1       
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# [100%]├░┼©ÔÇÿÔÇ░ Disabilito TLS e socket systemd standard...├░┼©ÔÇÿÔÇ░ Creo unit systemd per agent plain...├░┼©ÔÇÿÔÇ░ Ricarico systemd...├░┼©ÔÇÿÔÇ░ Abilito e avvio il nuovo socket...├ó┼ôÔÇª Plain agent attivo. Test locale:<<<check_mk>>>Version: 2.4.0p12Hostname: rocky01AgentOS: linuxUptime: 4321
